import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
from langchain_core.tools import tool
import re

load_dotenv()
@tool
def send_email(subject: str, body: str, recipient_override: str = ""):
    """Sends an email with the given subject and body in HTML format."""
    sender = os.getenv("EMAIL_ADDRESS")
    password = os.getenv("EMAIL_PASSWORD")
    recipient = recipient_override if recipient_override else os.getenv("RECEIVER_EMAIL")

    # formatted_body = body.replace('**', '<b>').replace('**', '</b>').replace('\n', '<br>')
    formatted_body = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', body).replace('\n', '<br>')


    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient

    html_body = f"""
    <html>
      <body>
        <h2>{subject}</h2>
        <p style="font-size: 14px;">{formatted_body}</p>
        <br>
        <p style="font-size:12px; color:gray;">This email was automatically generated by your personal recipe assistant.</p>
      </body>
    </html>
    """

    part = MIMEText(html_body, "html")
    msg.attach(part)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())
